name: graybox_abp_mpc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # You may want to adjust this version
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pytorch=2.0.0
  - casadi=3.5.5
  - gsd=2.5.2
  - hoomd=3.8.1
  - numba=0.56.4